-- Scraping Sources Schema

CREATE TABLE public.scraping_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id UUID REFERENCES public.personas(id) ON DELETE CASCADE NOT NULL,
  platform TEXT NOT NULL,
  source_url TEXT NOT NULL,
  last_checked TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.scraping_sources ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated users (or public for MVP)
CREATE POLICY "Enable read access for all users" ON public.scraping_sources FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.scraping_sources FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.scraping_sources FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.scraping_sources FOR DELETE USING (true);
