-- File browser and storage schema

CREATE TABLE public.files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('folder', 'file')),
  name TEXT NOT NULL,
  parent_id BIGINT REFERENCES public.files(id) ON DELETE CASCADE,
  persona_id UUID REFERENCES public.personas(id) ON DELETE SET NULL,
  size TEXT,
  url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated users (or public for MVP)
CREATE POLICY "Enable read access for all users" ON public.files FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.files FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.files FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.files FOR DELETE USING (true);
