import { useState, useEffect } from 'react';
import { X, Loader2, CheckCircle, FileText } from 'lucide-react';
import './TranscriptionModal.css';

export default function TranscriptionModal({ file, onClose }) {
  const [status, setStatus] = useState('idle'); // idle, transcribing, complete
  const [progress, setProgress] = useState(0);
  const [transcript, setTranscript] = useState('');

  useEffect(() => {
    const existing = localStorage.getItem(`transcript_${file.id}`);
    if (existing) {
      setTranscript(existing);
      setStatus('complete');
    }
  }, [file.id]);

  useEffect(() => {
    if (status === 'transcribing') {
      // Mock transcription process
      const interval = setInterval(() => {
        setProgress(p => {
          if (p >= 100) {
            clearInterval(interval);
            setStatus('complete');
            setTranscript("This is a scaffolded mock transcript. In a real scenario, this text would be generated by sending the audio file to an API like OpenAI Whisper or Deepgram, then updating this state with the response.");
            return 100;
          }
          return p + Math.floor(Math.random() * 15);
        });
      }, 500);
      return () => clearInterval(interval);
    }
  }, [status]);

  const handleStart = () => {
    setStatus('transcribing');
    setProgress(0);
  };

  return (
    <div className="modal-overlay">
      <div className="transcription-modal">
        <div className="modal-header">
          <h3><FileText size={16} /> Transcribe Audio</h3>
          <button className="close-btn" onClick={onClose}><X size={18} /></button>
        </div>

        <div className="modal-content">
          <div className="file-info">
            <span className="file-name">{file.name}</span>
            <span className="file-size">{file.size}</span>
          </div>

          {status === 'idle' && (
            <div className="idle-state">
              <p>Generate a transcript using AI audio processing.</p>
              <button className="primary-btn" onClick={handleStart}>Start Transcription</button>
            </div>
          )}

          {status === 'transcribing' && (
            <div className="transcribing-state">
              <div className="progress-bar-container">
                <div className="progress-bar" style={{ width: `${Math.min(progress, 100)}%` }}></div>
              </div>
              <p className="status-text"><Loader2 size={14} className="spin" /> Transcribing... {Math.min(progress, 100)}%</p>
            </div>
          )}

          {status === 'complete' && (
            <div className="complete-state">
              <p className="status-text success"><CheckCircle size={14} /> Transcription Complete</p>
              <textarea 
                className="transcript-editor" 
                value={transcript}
                onChange={(e) => setTranscript(e.target.value)}
                placeholder="Transcript will appear here..."
              />
              <button className="primary-btn" onClick={() => {
                localStorage.setItem(`transcript_${file.id}`, transcript);
                onClose();
              }}>
                Save & Close
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
